version: "3.9"

services:
  go-app:
    container_name: go-app
    image: go-api
    build: .
    ports:
      - "8003:8003"
    depends_on:
        - go_db
  go_db:
    container_name: go_db #Nome do container
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: #Mapeando um volume do docker no computador
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}      